### ISSUE TITLE
Space between "de" and "puis" in images/user-stats.png

### ISSUE THREAD

**Issue by DavidBruant** [bayesimpact/bob-emploi#32]
https://github.com/bayesimpact/bob-emploi/blob/6b9c9866cc127c412b5c58b0363f7f483d0f4fb1/frontend/src/images/user-stats.png

Arguably, this image should probably be HTML + CSS (or a React component) built from the data.

**Comment by pcorpet** [comment]
Ouch, thanks for catching. I will fix it for next release (and there's also a typo "créé" -> "créés").

**Comment by pcorpet** [comment]
I forgot to mark this as closed, but this was done a while back.
