### ISSUE TITLE
docker - unable to run and build the frontend

### ISSUE THREAD

**Issue by bertillepicard** [bayesimpact/bob-emploi#54]
I tried to run and build the frontend using the command `docker-compose up -d frontend-dev`, but it does not work. One row of code seems to run indefinitely. I tried it on different versions of the GitHub. I also have an error with the test command. Would you have a suggestion? Is there a problem only with the most recent version of docker?

![bug_docker](https://user-images.githubusercontent.com/52250335/118627582-252f4b80-b7cc-11eb-940b-e93cba02a81e.png)

Thanks in advance

**Comment by pcorpet** [comment]
Hi @Bbertt, thanks for trying out Bob. Apparently we're not ready for Docker Buildkit yet. I suggest you disable it:
```
DOCKER_BUILDKIT=0 docker-compose up -d frontend-dev
```

**Comment by Bbertt** [comment]
Thanks a lot for your answer. This command returned an error for some reason so I tried to disable Docker Buildkit permanently following [this post on stackoverflow](https://stackoverflow.com/a/66839653). However, the same step is still running indefinitely. Which version of Docker are you using? Maybe I can try with an older one.

**Comment by pcorpet** [comment]
I've done a more recent export of our internal code and made sur it ran at least on the CI pipeline.

The CI pipeline runs on `docker 19.03.13`, and on my dev machine I am on `docker 20.10.6`.

**Comment by Bbertt** [comment]
Thanks a lot, it works for me now! I was wondering if it was possible to try out older versions of Bob the same way, since their is a complete commit history on your GitHub ? I was curious about Bob's improvements over time. I am not an expert so I just tried downloading the old repo and running the same command but it does not work. I was not sure if it was because the old versions do not contain the recent added files or if it was just impossible.

**Comment by zozoens31** [comment]
Hi @Bbertt! What you did should work pretty well. There might be some issues with dependencies, though, we've started fixing them quite recently. What version of Bob have you tried? What issue did you encounter? I could explore it a bit for you if you want.

If you want to have an idea of what we did in Bob over time, you should also take a look at HISTORY.md (although we haven't updated it enough in the last two years, even though we have been working on it).

**Comment by pcorpet** [comment]
I've been able to reproduce and fix the issue.
